# Generated by Django 2.1.1 on 2018-09-05 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=64, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StuDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=30)),
                ('sex', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('stu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relation.Student')),
            ],
        ),
    ]
