# Generated by Django 2.1.1 on 2018-09-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studetail',
            table='stu_detail',
        ),
    ]
