# Generated by Django 2.1.1 on 2018-09-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0006_auto_20180905_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studetail',
            old_name='stu',
            new_name='stu_id',
        ),
    ]
